/**
 * V3-WALLET-004 — the complete wallet event log (tier 1): every one of the
 * 13 named event kinds, generated by comparing a previous and current
 * `PortfolioIntelligence` snapshot (content kinds) or wallet/network/refresh
 * state (lifecycle kinds). Pure and deterministic — same two inputs in,
 * same `WalletEvent[]` out, `timestamp` always taken from `current.lastUpdated`
 * (content) or the caller-supplied lifecycle timestamp, never `Date.now()`.
 *
 * This is the complete, unfiltered log ("Recent Wallet Events" reads this
 * directly) — a broader set than the 6 automation rules in `rules.ts`,
 * which only act on some of these kinds. Not every event here is
 * notify-worthy; all of them are honest, real state transitions.
 */

import type { PortfolioIntelligence } from "@/lib/portfolio-intelligence/types";
import { buildSmartMetadata, type SmartMetadataFocus } from "@/lib/wallet-automation/smartMetadata";
import * as smartTriggers from "@/lib/wallet-automation/smartTriggers";
import * as triggers from "@/lib/wallet-automation/triggers";
import {
  buildContentEventCopy,
  buildLifecycleEventCopy,
  buildSmartContentEventCopy,
  type ContentEventKind,
  type LifecycleEventKind,
  type SmartContentEventKind,
} from "@/lib/wallet-automation/summary";
import type { WalletEvent, WalletLifecycleState } from "@/lib/wallet-automation/types";

function makeContentEvent(kind: ContentEventKind, timestamp: string, previous: PortfolioIntelligence | null, current: PortfolioIntelligence, tone: WalletEvent["tone"]): WalletEvent {
  const { title, summary } = buildContentEventCopy(kind, previous, current);
  return { id: `wallet-event:${kind}:${timestamp}`, kind, timestamp, title, summary, tone };
}

function makeLifecycleEvent(kind: LifecycleEventKind, timestamp: string, tone: WalletEvent["tone"]): WalletEvent {
  const { title, summary } = buildLifecycleEventCopy(kind);
  return { id: `wallet-event:${kind}:${timestamp}`, kind, timestamp, title, summary, tone };
}

/** The 9 content-diff kinds only — never called with `current === null` since there's nothing to diff without a real snapshot. */
export function buildPortfolioContentEvents(previous: PortfolioIntelligence | null, current: PortfolioIntelligence): WalletEvent[] {
  const events: WalletEvent[] = [];
  const t = current.lastUpdated;

  if (triggers.scoreChangedSignificantly(previous, current)) {
    events.push(makeContentEvent("PortfolioScoreChanged", t, previous, current, current.overallScore >= (previous?.overallScore ?? 0) ? "positive" : "attention"));
  }
  if (triggers.riskLevelChanged(previous, current)) {
    events.push(makeContentEvent("RiskLevelChanged", t, previous, current, current.concentrationRisk.level === "high" || current.concentrationRisk.level === "elevated" ? "attention" : "neutral"));
  }
  if (triggers.concentrationJustExceededHigh(previous, current)) {
    events.push(makeContentEvent("ConcentrationThresholdExceeded", t, previous, current, "attention"));
  }
  if (triggers.stablecoinExposureJustDropped(previous, current)) {
    events.push(makeContentEvent("StablecoinExposureDropped", t, previous, current, "attention"));
  }
  if (triggers.stablecoinExposureJustRecovered(previous, current)) {
    events.push(makeContentEvent("StablecoinExposureRecovered", t, previous, current, "positive"));
  }
  if (triggers.pricingCoverageJustDropped(previous, current)) {
    events.push(makeContentEvent("PricingCoverageDropped", t, previous, current, "attention"));
  }
  if (triggers.pricingCoverageJustRecovered(previous, current)) {
    events.push(makeContentEvent("PricingCoverageRecovered", t, previous, current, "positive"));
  }
  if (triggers.unknownAssetsIncreased(previous, current)) {
    events.push(makeContentEvent("UnknownAssetsDetected", t, previous, current, "neutral"));
  }
  if (triggers.largestHoldingChanged(previous, current)) {
    events.push(makeContentEvent("LargestHoldingChanged", t, previous, current, "neutral"));
  }
  if (triggers.portfolioValueChangedSignificantly(previous, current)) {
    events.push(makeContentEvent("PortfolioValueChanged", t, previous, current, current.totalUsdValue >= (previous?.totalUsdValue ?? 0) ? "positive" : "attention"));
  }

  return events;
}

/** `SmartContentEventKind` → the `SmartMetadataFocus` it's about, for `buildSmartMetadata` (`smartMetadata.ts`, shared with `engine.ts`'s smart `AutomationResult`s). */
const METADATA_FOCUS_BY_KIND: Record<SmartContentEventKind, SmartMetadataFocus> = {
  ConfidenceIncreased: "general",
  ConfidenceDropped: "general",
  FingerprintChanged: "general",
  PrimaryRecommendationChanged: "general",
  RiskIncreased: "general",
  RiskDecreased: "general",
  LargestProtocolChanged: "largest-protocol",
  TopContributorChanged: "top-contributor",
  TopWarningChanged: "top-warning",
};

function makeSmartContentEvent(kind: SmartContentEventKind, timestamp: string, previous: PortfolioIntelligence | null, current: PortfolioIntelligence, tone: WalletEvent["tone"]): WalletEvent {
  const { title, summary } = buildSmartContentEventCopy(kind, previous, current);
  return { id: `wallet-event:${kind}:${timestamp}`, kind, timestamp, title, summary, tone, metadata: buildSmartMetadata(current, METADATA_FOCUS_BY_KIND[kind]) };
}

/**
 * V4-AUTOMATION-001 (Phase 3) — the 9 new smart content kinds, mirroring
 * `buildPortfolioContentEvents`'s exact shape (own function, never called
 * with `current === null`) rather than extending that function — keeps it
 * byte-for-byte what it was, per this phase's "keep the existing engine
 * unchanged" instruction. Every trigger predicate lives in
 * `smartTriggers.ts`; nothing here recomputes a score or condition.
 */
export function buildSmartPortfolioEvents(previous: PortfolioIntelligence | null, current: PortfolioIntelligence): WalletEvent[] {
  const events: WalletEvent[] = [];
  const t = current.lastUpdated;

  if (smartTriggers.confidenceIncreased(previous, current)) {
    events.push(makeSmartContentEvent("ConfidenceIncreased", t, previous, current, "positive"));
  }
  if (smartTriggers.confidenceDropped(previous, current)) {
    events.push(makeSmartContentEvent("ConfidenceDropped", t, previous, current, "attention"));
  }
  if (smartTriggers.fingerprintChanged(previous, current)) {
    events.push(makeSmartContentEvent("FingerprintChanged", t, previous, current, "neutral"));
  }
  if (smartTriggers.primaryRecommendationChanged(previous, current)) {
    events.push(makeSmartContentEvent("PrimaryRecommendationChanged", t, previous, current, "neutral"));
  }
  if (smartTriggers.riskScoreIncreased(previous, current)) {
    events.push(makeSmartContentEvent("RiskIncreased", t, previous, current, "attention"));
  }
  if (smartTriggers.riskScoreDecreased(previous, current)) {
    events.push(makeSmartContentEvent("RiskDecreased", t, previous, current, "positive"));
  }
  if (smartTriggers.largestProtocolChanged(previous, current)) {
    events.push(makeSmartContentEvent("LargestProtocolChanged", t, previous, current, "neutral"));
  }
  if (smartTriggers.topContributorChanged(previous, current)) {
    events.push(makeSmartContentEvent("TopContributorChanged", t, previous, current, "attention"));
  }
  if (smartTriggers.topWarningChanged(previous, current)) {
    events.push(makeSmartContentEvent("TopWarningChanged", t, previous, current, "attention"));
  }

  return events;
}

/** The 4 lifecycle kinds — driven by wallet/network/refresh state, since `PortfolioIntelligence` doesn't exist while disconnected and carries no connection concept. */
export function buildLifecycleEvents(previous: WalletLifecycleState | null, current: WalletLifecycleState, timestamp: string): WalletEvent[] {
  if (!previous) return [];
  const events: WalletEvent[] = [];

  if (!previous.isConnected && current.isConnected) {
    events.push(makeLifecycleEvent("WalletConnected", timestamp, "positive"));
  }
  if (previous.isConnected && !current.isConnected) {
    events.push(makeLifecycleEvent("WalletDisconnected", timestamp, "neutral"));
  }
  if (current.isConnected && (!current.isSupportedNetwork || !current.chainSupported) && previous.isSupportedNetwork && previous.chainSupported) {
    events.push(makeLifecycleEvent("UnsupportedNetwork", timestamp, "attention"));
  }
  if (current.isConnected && previous.lastUpdated !== current.lastUpdated && current.lastUpdated !== null) {
    events.push(makeLifecycleEvent("RefreshCompleted", timestamp, "neutral"));
  }

  return events;
}
