/**
 * Realistic local mock alerts for the Alert Engine foundation — no
 * provider call, no network request, computed once at module load.
 * `projectId`/`projectName` pairs are real entries from the Project
 * Registry (`data/projects/seed/`) so a future PR wiring `AlertCard`'s
 * project logo up to `getProject(projectId)` resolves real data; the
 * alert content itself (title/summary/timestamps) is fabricated for
 * demonstration only, never presented as live intelligence.
 *
 * Timestamps are computed relative to `Date.now()` at import time (rather
 * than fixed ISO strings) so the feed always reads as "recent" whenever
 * the app runs, instead of visibly going stale after this PR ships.
 */

import type { Alert } from "@/lib/alerts/types";

function minutesAgo(minutes: number): string {
  return new Date(Date.now() - minutes * 60_000).toISOString();
}

export const MOCK_ALERTS: Alert[] = [
  {
    id: "alert-001",
    projectId: "aave",
    projectName: "Aave",
    title: "New Governance Proposal Opened",
    summary: "AIP-412 proposes adjusting the collateral factor for cbBTC markets on Base.",
    category: "governance",
    severity: "info",
    timestamp: minutesAgo(35),
    read: false,
    pinned: true,
    source: "Snapshot",
    actionUrl: "/dashboard/projects/aave",
  },
  {
    id: "alert-002",
    projectId: "compound",
    projectName: "Compound",
    title: "v3.4.0 Released",
    summary: "Improved liquidation engine and gas optimizations for Base deployments.",
    category: "release",
    severity: "info",
    timestamp: minutesAgo(90),
    read: false,
    pinned: false,
    source: "GitHub",
    actionUrl: "/dashboard/projects/compound",
  },
  {
    id: "alert-003",
    projectId: "aerodrome-finance",
    projectName: "Aerodrome Finance",
    title: "TVL Increased 18% This Week",
    summary: "Total value locked climbed to $612M following new incentive gauges.",
    category: "tvl",
    severity: "success",
    timestamp: minutesAgo(180),
    read: true,
    pinned: false,
    source: "DefiLlama",
    actionUrl: "/dashboard/projects/aerodrome-finance",
  },
  {
    id: "alert-004",
    projectId: "curve-finance",
    projectName: "Curve Finance",
    title: "Liquidity Pool Rebalanced",
    summary: "The USDC/cbBTC pool depth grew 24% after a new gauge vote passed.",
    category: "liquidity",
    severity: "info",
    timestamp: minutesAgo(260),
    read: true,
    pinned: false,
    source: "DexScreener",
    actionUrl: "/dashboard/projects/curve-finance",
  },
  {
    id: "alert-005",
    projectId: "morpho",
    projectName: "Morpho",
    title: "Whale Accumulated 2.4M Tokens",
    summary: "A single wallet acquired $2.4M of MORPHO across three transactions in the last hour.",
    category: "whale",
    severity: "warning",
    timestamp: minutesAgo(340),
    read: false,
    pinned: false,
    source: "Blockscout",
    actionUrl: "/dashboard/projects/morpho",
  },
  {
    id: "alert-006",
    projectId: "layerzero",
    projectName: "LayerZero",
    title: "Security Advisory Published",
    summary: "A low-severity issue in an auxiliary relayer contract was disclosed and patched.",
    category: "security",
    severity: "critical",
    timestamp: minutesAgo(420),
    read: false,
    pinned: true,
    source: "Registry",
    actionUrl: "/dashboard/projects/layerzero",
  },
  {
    id: "alert-007",
    projectId: "safe",
    projectName: "Safe",
    title: "Strategic Partnership Announced",
    summary: "Safe is integrating natively with a major Base-native wallet provider.",
    category: "partnership",
    severity: "success",
    timestamp: minutesAgo(600),
    read: true,
    pinned: false,
    source: "Registry",
    actionUrl: "/dashboard/projects/safe",
  },
  {
    id: "alert-008",
    projectId: "virtuals-protocol",
    projectName: "Virtuals Protocol",
    title: "Now Listed on Coinbase",
    summary: "VIRTUAL is now available for trading on Coinbase's exchange.",
    category: "listing",
    severity: "success",
    timestamp: minutesAgo(720),
    read: false,
    pinned: false,
    source: "CoinGecko",
    actionUrl: "/dashboard/projects/virtuals-protocol",
  },
  {
    id: "alert-009",
    projectId: "uniswap",
    projectName: "Uniswap",
    title: "Protocol Upgrade Scheduled",
    summary: "A router upgrade improving multi-hop swap efficiency is scheduled for next week.",
    category: "upgrade",
    severity: "info",
    timestamp: minutesAgo(900),
    read: true,
    pinned: false,
    source: "GitHub",
    actionUrl: "/dashboard/projects/uniswap",
  },
  {
    id: "alert-010",
    projectId: "basenames",
    projectName: "Basenames",
    title: "New Integration With Base Ecosystem Wallets",
    summary: "Three additional wallet providers now support Basenames resolution by default.",
    category: "ecosystem",
    severity: "info",
    timestamp: minutesAgo(1080),
    read: false,
    pinned: false,
    source: "Registry",
    actionUrl: "/dashboard/projects/basenames",
  },
  {
    id: "alert-011",
    projectId: "pyth-network",
    projectName: "Pyth Network",
    title: "Price Up 12% in 24 Hours",
    summary: "PYTH rallied alongside broader oracle-sector momentum.",
    category: "price",
    severity: "success",
    timestamp: minutesAgo(1260),
    read: true,
    pinned: false,
    source: "CoinGecko",
    actionUrl: "/dashboard/projects/pyth-network",
  },
  {
    id: "alert-012",
    projectId: "farcaster",
    projectName: "Farcaster",
    title: "Community Call Recap Published",
    summary: "This month's ecosystem call covered protocol roadmap and grant recipients.",
    category: "community",
    severity: "info",
    timestamp: minutesAgo(1440),
    read: true,
    pinned: false,
    source: "Registry",
    actionUrl: "/dashboard/projects/farcaster",
  },
  {
    id: "alert-013",
    projectId: "compound",
    projectName: "Compound",
    title: "Voting Period Ending Soon",
    summary: "AIP-89 closes for voting in less than 24 hours with quorum not yet reached.",
    category: "governance",
    severity: "warning",
    timestamp: minutesAgo(1620),
    read: false,
    pinned: false,
    source: "Snapshot",
    actionUrl: "/dashboard/projects/compound",
  },
  {
    id: "alert-014",
    projectId: "safe",
    projectName: "Safe",
    title: "Hotfix Released for Critical Bug",
    summary: "An urgent patch addresses a transaction-simulation edge case affecting multisig approvals.",
    category: "release",
    severity: "critical",
    timestamp: minutesAgo(1800),
    read: false,
    pinned: true,
    source: "GitHub",
    actionUrl: "/dashboard/projects/safe",
  },
  {
    id: "alert-015",
    projectId: "extra-finance",
    projectName: "Extra Finance",
    title: "TVL Declined 9% Amid Market Volatility",
    summary: "Leveraged positions were partially unwound following broader market weakness.",
    category: "tvl",
    severity: "warning",
    timestamp: minutesAgo(2160),
    read: true,
    pinned: false,
    source: "DefiLlama",
    actionUrl: "/dashboard/projects/extra-finance",
  },
  {
    id: "alert-016",
    projectId: "moonwell",
    projectName: "Moonwell",
    title: "Large Withdrawal Detected",
    summary: "A wallet withdrew $1.8M in collateral within a single block.",
    category: "whale",
    severity: "warning",
    timestamp: minutesAgo(2880),
    read: false,
    pinned: false,
    source: "Blockscout",
    actionUrl: "/dashboard/projects/moonwell",
  },
  {
    id: "alert-017",
    projectId: "balancer",
    projectName: "Balancer",
    title: "Audit Completed With No Critical Findings",
    summary: "An independent security review of the v3 vault contracts closed with zero critical issues.",
    category: "security",
    severity: "success",
    timestamp: minutesAgo(4320),
    read: true,
    pinned: false,
    source: "Registry",
    actionUrl: "/dashboard/projects/balancer",
  },
  {
    id: "alert-018",
    projectId: "clanker",
    projectName: "Clanker",
    title: "Delisted From Minor Exchange",
    summary: "Trading was suspended on a smaller centralized exchange citing low volume.",
    category: "listing",
    severity: "warning",
    timestamp: minutesAgo(5760),
    read: true,
    pinned: false,
    source: "CoinGecko",
    actionUrl: "/dashboard/projects/clanker",
  },
  {
    id: "alert-019",
    projectId: "across-protocol",
    projectName: "Across Protocol",
    title: "Mainnet Upgrade Completed Successfully",
    summary: "The new intent-based relayer network is now live across all supported chains.",
    category: "upgrade",
    severity: "success",
    timestamp: minutesAgo(7200),
    read: false,
    pinned: false,
    source: "GitHub",
    actionUrl: "/dashboard/projects/across-protocol",
  },
  {
    id: "alert-020",
    projectId: "seamless-protocol",
    projectName: "Seamless Protocol",
    title: "Price Down 8% Following Broader Market Dip",
    summary: "SEAM tracked a wider pullback across Base-native governance tokens.",
    category: "price",
    severity: "warning",
    timestamp: minutesAgo(8640),
    read: true,
    pinned: false,
    source: "CoinGecko",
    actionUrl: "/dashboard/projects/seamless-protocol",
  },
  {
    id: "alert-021",
    projectId: "usd-coin",
    projectName: "USD Coin",
    title: "10,000 Discord Members Milestone",
    summary: "The developer community server crossed 10,000 members this week.",
    category: "community",
    severity: "success",
    timestamp: minutesAgo(10080),
    read: false,
    pinned: false,
    source: "Registry",
    actionUrl: "/dashboard/projects/usd-coin",
  },
  {
    id: "alert-022",
    projectId: "layerzero",
    projectName: "LayerZero",
    title: "Deployed to New L2 Network",
    summary: "LayerZero's messaging layer now supports a newly launched Base-aligned L2.",
    category: "ecosystem",
    severity: "info",
    timestamp: minutesAgo(15840),
    read: true,
    pinned: false,
    source: "Registry",
    actionUrl: "/dashboard/projects/layerzero",
  },
];
