/**
 * AI Alert Intelligence (PR15.3 Part 1) — a derived, ADDITIVE layer on top
 * of the existing `Alert` model (`lib/alerts/types.ts`), never a
 * replacement for it. Every `IntelligenceAlert` below is built entirely
 * from real, already-fetched `Alert`s (see `lib/alerts/intelligence/engine.ts`);
 * nothing here is generated by an LLM or any external AI service —
 * `narrative`/`headline`/`summary`/`reasoning` are all deterministic
 * template output over real signals, the same "real data in, plain-English
 * text out" rule this codebase has followed since `lib/intelligence`'s
 * report-building (`lib/intelligence/report.ts`).
 */

import type { Alert, AlertCategory, AlertSeverity } from "@/lib/alerts/types";

/**
 * One real, already-computed contribution to a project's Intelligence
 * Alert — always traceable back to a real `Alert` via `sourceAlertId`,
 * never a synthetic/imagined factor.
 */
export type IntelligenceSignal = {
  category: AlertCategory;
  /** Short, human-readable label for this signal, e.g. "TVL change" or "Whale activity". */
  label: string;
  /** Always >= 0 — how much this signal contributes to the project's overall score/importance, regardless of direction. */
  weight: number;
  /** -1 negative, 0 neutral/procedural, 1 positive — derived from the source alert's own real title text (see `scoring.ts`'s `classifyDirection`), never guessed beyond what that alert already says. */
  direction: -1 | 0 | 1;
  sourceAlertId: Alert["id"];
};

/**
 * The finite set of deterministic patterns the rule-based engine can
 * recognize — every one requires real, specific signal co-occurrence (see
 * `narratives.ts`); there is no fallback "AI-sounding" narrative invented
 * when the real signals don't clearly support one — `"stable"` is that
 * honest fallback.
 */
export const NARRATIVE_TYPES = [
  "growth",
  "decline",
  "governance-active",
  "security-risk",
  "accumulation",
  "development-active",
  "stable",
] as const;
export type NarrativeType = (typeof NARRATIVE_TYPES)[number];

/**
 * One project's rolled-up intelligence summary for the CURRENT batch of
 * (already Watchlist-visible) alerts. Rebuilt every time the underlying
 * alert set changes — never persisted, never mutated in place, so it's
 * always a fresh, honest reflection of `relatedAlertIds`.
 */
export type IntelligenceAlert = {
  /** Deterministic and stable for a given project — `intelligence:${projectId}` — so re-running the pipeline on an unchanged alert set produces the identical id. */
  id: string;
  projectId: string;
  projectName: string;
  /** The most severe real severity among `relatedAlertIds` — never invented independently of the alerts it summarizes. */
  severity: AlertSeverity;
  /** 0-100 — how much real, corroborating signal (independent signal CATEGORIES agreeing, not just alert count) backs this summary. */
  confidence: number;
  headline: string;
  summary: string;
  signals: IntelligenceSignal[];
  categories: AlertCategory[];
  /** 0-100 bounded composite of every contributing signal's weight — the magnitude/importance of what's happening, not how sure the engine is it's real (that's `confidence`). */
  score: number;
  relatedAlertIds: string[];
  /** The most recent `timestamp` among `relatedAlertIds`. */
  timestamp: string;
  /** One-line, human-readable explanation of why this score/narrative was chosen — real factors only (signal count, category count), never a fabricated justification. */
  reasoning: string;
  /** A short, actionable pointer to where the user should look next — deterministic, keyed off the real `narrative` (see `summary.ts`'s `buildNextStep`), never project-specific speculation the signals don't support. */
  nextStep: string;
  narrative: NarrativeType;
};
