/**
 * V4-FUTURE-002 (Feature 7 — Smart Report Sharing) — "Reuse Report Export.
 * Do not rebuild formatting." Every section this file assembles is either
 * `buildReportExportSections(report)` (Historical Report Export's own
 * builder, reused verbatim — always included, it IS the report being
 * shared) or a direct, deterministic read of an already-built object,
 * folded through the SAME shared `lib/export/render.ts` renderers every
 * other export feature in this app uses. No new Markdown/HTML/text
 * renderer, no new scoring, no new correlation — this file only SELECTS
 * and COMBINES.
 */

import type { ExportSection } from "@/lib/export/sections";
import { buildReportExportSections } from "@/lib/report-export/sections";
import { buildDigestOnlyExportSections } from "@/lib/monthly-digest/sections";
import { buildStoryOnlyExportSections } from "@/lib/portfolio-story/sections";
import { REPORT_PERIOD_LABEL } from "@/components/wallet/walletReportEngine";
import { buildShareProfile } from "@/lib/share/build";
import type { ShareProfile } from "@/lib/share/types";
import type { ShareIncludeOptions, ShareSourceData } from "@/lib/report-share/types";

const USD_FORMAT = new Intl.NumberFormat("en-US", { style: "currency", currency: "USD", maximumFractionDigits: 0 });

export function buildShareTitle(data: ShareSourceData): string {
  return `Base Radar — Portfolio Report (${REPORT_PERIOD_LABEL[data.report.period]})`;
}

/** A real, deterministic fact string off `report.overview` — never a generated sentence. */
export function buildShareSummary(data: ShareSourceData): string {
  const { snapshotCount, netValueChange } = data.report.overview;
  const parts = [`${snapshotCount} snapshot${snapshotCount === 1 ? "" : "s"}`];
  if (netValueChange !== null) parts.push(`${netValueChange >= 0 ? "+" : ""}${USD_FORMAT.format(netValueChange)} net change`);
  return parts.join(", ");
}

/** Reuses `ai.overview.explanation` verbatim when a real advisor read exists — never a second summary. Falls back to a plain, honest fact when there's no AI overview to reuse. */
export function buildShareDescription(data: ShareSourceData): string {
  return data.ai?.overview.explanation ?? `${REPORT_PERIOD_LABEL[data.report.period]} portfolio report generated by Base Radar.`;
}

function buildShareSections(data: ShareSourceData, options: ShareIncludeOptions): ExportSection[] {
  const sections = buildReportExportSections(data.report);

  if (options.history) {
    sections.push({
      title: "Snapshot History",
      rows: [
        { label: "Total Snapshots", value: String(data.history.snapshotCount) },
        ...(data.history.oldestSnapshot ? [{ label: "First Snapshot", value: data.history.oldestSnapshot.timestamp }] : []),
        ...(data.history.newestSnapshot ? [{ label: "Latest Snapshot", value: data.history.newestSnapshot.timestamp }] : []),
      ],
    });
  }

  if (options.timeline) {
    sections.push({ title: "Timeline", rows: data.crossFeature.timeline.map((entry) => ({ label: entry.timestamp, value: entry.headline })) });
  }

  if (options.recommendations) {
    sections.push({ title: "Recommendations", rows: (data.intelligence?.recommendations ?? []).map((r) => ({ label: r.title, value: r.reason })) });
  }

  // All-time highlights (`analytics.highlights`), distinct from the base
  // report's own PERIOD-scoped "Highlights" section above — useful when
  // sharing a short period but wanting the broader picture too.
  if (options.highlights) {
    sections.push({ title: "All-Time Highlights", rows: data.analytics.highlights.map((h) => ({ label: h.title, value: h.reason })) });
  }

  if (options.digest && data.digest) sections.push(...buildDigestOnlyExportSections(data.digest));
  if (options.story && data.story) sections.push(...buildStoryOnlyExportSections(data.story));

  return sections;
}

export function buildSharePreview(data: ShareSourceData, options: ShareIncludeOptions, generatedAt: string = new Date().toISOString()): ShareProfile {
  return buildShareProfile({
    title: buildShareTitle(data),
    summary: buildShareSummary(data),
    description: buildShareDescription(data),
    sections: buildShareSections(data, options),
    generatedAt,
  });
}
